### ISSUE TITLE
New Slogan

### ISSUE THREAD

**Issue by jacoobes** [sern-handler/docs#60]
current slogan is very ambiguous. I want it to 

- describe what sern does
- keep it short
- have at least discord in it
- Redesign the homepage

**Comment by Peter-MJ-Parker** [comment]
CLI Magic: from novice to Discord Bot master in no time!
Empower your Discord community with sern!
Unleash the power of Discord with sern-handler!
Level up your Discord experience with sern: Where bot management meets excellence!
sern: revolutionizing Discord Bot development at your fingertips!
